# Default values for vaultwarden-ldap-sync.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: vividboarder/vaultwarden_ldap
  pullPolicy: IfNotPresent
  tag: "0.6.2-alpine"

config:
  sync_interval: "60"
  vaultwarden:
    url: http://vautlwarden:80
    admin_token: admin
  ldap:
    host: ldap.domain.local
    bind:
      dn: cn=admin,dc=domain,dc=local
      password: P@ssw0rd
    search:
      base_dn: dc=domain,dc=local
      filter: (&(objectClass=*)(uid=*))

extraEnvVars: {}

secretName: ldap-sync-config

ressources:
  limits:
    cpu: 1
    memory: 1024Mi
