apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
type: Opaque
stringData:
  config.toml: |
    vaultwarden_url = "{{ .Vaulues.config.vaultwarden.url }}"
    vaultwarden_admin_token = "{{ .Vaulues.config.vaultwarden.admin_token }}"
    ldap_host = "{{ .Vaulues.config.ldap.host }}"
    ldap_bind_dn = "{{ .Vaulues.config.ldap.bind.dn }}"
    ldap_bind_password = "{{ .Vaulues.config.ldap.bind.password }}"
    ldap_search_base_dn = "{{ .Vaulues.config.ldap.search.base_dn }}"
    ldap_search_filter = "{{ .Vaulues.config.ldap.search.filter }}"
    ldap_sync_interval_seconds = {{ .Vaulues.config.sync_interval }}
