apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
type: Opaque
stringData:
  config.toml: |
    vaultwarden_url = "{{ .Values.config.vaultwarden.url }}"
    vaultwarden_admin_token = "{{ .Values.config.vaultwarden.admin_token }}"
    ldap_host = "{{ .Values.config.ldap.host }}"
    ldap_bind_dn = "{{ .Values.config.ldap.bind.dn }}"
    ldap_bind_password = "{{ .Values.config.ldap.bind.password }}"
    ldap_search_base_dn = "{{ .Values.config.ldap.search.base_dn }}"
    ldap_search_filter = "{{ .Values.config.ldap.search.filter }}"
    ldap_sync_interval_seconds = {{ .Values.config.sync_interval }}
